name: Auto Ready Pull Request

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read
  pull-requests: write

jobs:
  mark-ready:
    runs-on: ubuntu-latest

    if: github.event.pull_request.draft == true

    steps:
      - name: Mark PR as ready for review
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr ready "$PR_URL"
